### ISSUE TITLE
How long do the containers hang around?

### ISSUE THREAD

**Issue by Deekor** [cryo28/sidekiq_status#34]
Do I need to be deleting them on the web UI?

**Comment by cryo28** [comment]
By default containers stay in redis [for 30 days](https://github.com/cryo28/sidekiq_status/blob/master/lib/sidekiq_status/container.rb#L26). But you can easily configure the retention period for each worker. Something like this:

```ruby
class MyWorker
  include SidekiqStatus::Container

  self.ttl = 300 # seconds
```

**Comment by Deekor** [comment]
Can this be adjusted globally for all workers?

**Comment by Deekor** [comment]
Also your example above does not work.

    wrong argument type Class (expected Module)

When trying `include SidekiqStatus::Container`

**Comment by cryo28** [comment]
Sorry I was sloppy in my answer. ttl is actually defined at `SidekiqStatus::Container` [here[(https://github.com/cryo28/sidekiq_status/blob/master/lib/sidekiq_status/container.rb#L25). And it will apply to all workers. Something like

```ruby
# config/initializers/sidekiq.rb

SidekiqStatus::Container.ttl = 600 seconds
```

**Comment by Deekor** [comment]
Ok so I set the ttl to 30 seconds and gave it a test. Now when I go to the statuses page in sidekiq (after they have expired) I am getting an error. 
![screen shot 2016-11-03 at 12 34 53 pm](https://cloud.githubusercontent.com/assets/1904267/19979977/fda28ab6-a1c1-11e6-84a0-58bf1488df13.png)

**Comment by Deekor** [comment]
I've tried updating the gem and the issue still exists. Any ideas?

**Comment by cryo28** [comment]
Could you please:

1. Clean your redis and try again. There is a just that you have some messed up data in it. Container#load expectes data to be a json object but it is null.
2. Show the error stacktrace

**Comment by Deekor** [comment]
Ok I flushed my redis db and set the timeout to 20 seconds. After the containers expire I get the same error. Here is the stack trace


   ```
TypeError - no implicit conversion of nil into Hash:
   () Users/dee/.rvm/gems/ruby-2.0.0-p643/bundler/gems/sidekiq_status-bd47d38d0ce6/lib/sidekiq_status/container.rb:327:in `load'
   () Users/dee/.rvm/gems/ruby-2.0.0-p643/bundler/gems/sidekiq_status-bd47d38d0ce6/lib/sidekiq_status/container.rb:187:in `initialize'
   () Users/dee/.rvm/gems/ruby-2.0.0-p643/bundler/gems/sidekiq_status-bd47d38d0ce6/lib/sidekiq_status/container.rb:139:in `block in load_multi'
   () Users/dee/.rvm/gems/ruby-2.0.0-p643/bundler/gems/sidekiq_status-bd47d38d0ce6/lib/sidekiq_status/container.rb:138:in `load_multi'
   () Users/dee/.rvm/gems/ruby-2.0.0-p643/bundler/gems/sidekiq_status-bd47d38d0ce6/lib/sidekiq_status/container.rb:93:in `statuses'
   () Users/dee/.rvm/gems/ruby-2.0.0-p643/bundler/gems/sidekiq_status-bd47d38d0ce6/lib/sidekiq_status/web.rb:35:in `block in registered'
  sidekiq (4.2.5) lib/sidekiq/web/application.rb:266:in `block in call'
  sidekiq (4.2.5) lib/sidekiq/web/application.rb:262:in `call'
  rack-protection (1.5.3) lib/rack/protection/xss_header.rb:18:in `call'
  rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
  rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
  rack-protection (1.5.3) lib/rack/protection/path_traversal.rb:16:in `call'
  rack-protection (1.5.3) lib/rack/protection/json_csrf.rb:18:in `call'
  rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
  rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
  rack-protection (1.5.3) lib/rack/protection/frame_options.rb:31:in `call'
  rack-protection (1.5.3) lib/rack/protection/base.rb:49:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  rack (1.6.4) lib/rack/urlmap.rb:66:in `block in call'
  rack (1.6.4) lib/rack/urlmap.rb:50:in `call'
  rack (1.6.4) lib/rack/builder.rb:153:in `call'
  sidekiq (4.2.5) lib/sidekiq/web.rb:103:in `call'
  sidekiq (4.2.5) lib/sidekiq/web.rb:108:in `call'
  actionpack (4.2.5) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  newrelic_rpm (3.13.2.302) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.0.3) lib/quiet_assets.rb:23:in `call_with_quiet_assets'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.6.2) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.2) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.2) lib/thin/connection.rb:53:in `process'
  thin (1.6.2) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
  thin (1.6.2) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.2) lib/thin/server.rb:162:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.5) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.5) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.5) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.5) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.5) lib/rails/commands.rb:17:in `<top (required)>'
   () Users/dee/Bookly/taxalli/bin/rails:8:in `<top (required)>'
  spring (1.3.6) lib/spring/client/rails.rb:28:in `call'
  spring (1.3.6) lib/spring/client/command.rb:7:in `call'
  spring (1.3.6) lib/spring/client.rb:26:in `run'
  spring (1.3.6) bin/spring:48:in `<top (required)>'
  spring (1.3.6) lib/spring/binstub.rb:11:in `<top (required)>'
   () Users/dee/Bookly/taxalli/bin/spring:16:in `<top (required)>'
   () rails:3:in `<main>'
```

**Comment by Deekor** [comment]
Any ideas on this?
